<?php
/**
 * ActivityApi
 * PHP version 5
 *
 * @category Class
 * @package  ExaVault
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ExaVault API
 *
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.22
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace ExaVault\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use ExaVault\ApiException;
use ExaVault\Configuration;
use ExaVault\HeaderSelector;
use ExaVault\ObjectSerializer;

/**
 * ActivityApi Class Doc Comment
 *
 * @category Class
 * @package  ExaVault
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ActivityApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getSessionLogs
     *
     * Get activity logs
     *
     * @param  string $evApiKey API Key (required)
     * @param  string $evAccessToken Access Token (required)
     * @param  \DateTime $startDate Start date of the filter data range (optional)
     * @param  \DateTime $endDate End date of the filter data range (optional)
     * @param  string $ipAddress Used to filter session logs by ip address. (optional)
     * @param  string $username Username used for filtering a list (optional)
     * @param  string $path Path used to filter records (optional)
     * @param  string $type Filter session logs for operation type (see table above for acceptable values) (optional)
     * @param  int $offset Offset of the records list (optional)
     * @param  int $limit Limit of the records list (optional)
     * @param  string $sort Comma separated list sort params (optional)
     *
     * @throws \ExaVault\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \ExaVault\Model\SessionActivityResponse
     */
    public function getSessionLogs($evApiKey, $evAccessToken, $startDate = null, $endDate = null, $ipAddress = null, $username = null, $path = null, $type = null, $offset = null, $limit = null, $sort = null)
    {
        list($response) = $this->getSessionLogsWithHttpInfo($evApiKey, $evAccessToken, $startDate, $endDate, $ipAddress, $username, $path, $type, $offset, $limit, $sort);
        return $response;
    }

    /**
     * Operation getSessionLogsWithHttpInfo
     *
     * Get activity logs
     *
     * @param  string $evApiKey API Key (required)
     * @param  string $evAccessToken Access Token (required)
     * @param  \DateTime $startDate Start date of the filter data range (optional)
     * @param  \DateTime $endDate End date of the filter data range (optional)
     * @param  string $ipAddress Used to filter session logs by ip address. (optional)
     * @param  string $username Username used for filtering a list (optional)
     * @param  string $path Path used to filter records (optional)
     * @param  string $type Filter session logs for operation type (see table above for acceptable values) (optional)
     * @param  int $offset Offset of the records list (optional)
     * @param  int $limit Limit of the records list (optional)
     * @param  string $sort Comma separated list sort params (optional)
     *
     * @throws \ExaVault\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \ExaVault\Model\SessionActivityResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSessionLogsWithHttpInfo($evApiKey, $evAccessToken, $startDate = null, $endDate = null, $ipAddress = null, $username = null, $path = null, $type = null, $offset = null, $limit = null, $sort = null)
    {
        $returnType = '\ExaVault\Model\SessionActivityResponse';
        $request = $this->getSessionLogsRequest($evApiKey, $evAccessToken, $startDate, $endDate, $ipAddress, $username, $path, $type, $offset, $limit, $sort);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ExaVault\Model\SessionActivityResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getSessionLogsAsync
     *
     * Get activity logs
     *
     * @param  string $evApiKey API Key (required)
     * @param  string $evAccessToken Access Token (required)
     * @param  \DateTime $startDate Start date of the filter data range (optional)
     * @param  \DateTime $endDate End date of the filter data range (optional)
     * @param  string $ipAddress Used to filter session logs by ip address. (optional)
     * @param  string $username Username used for filtering a list (optional)
     * @param  string $path Path used to filter records (optional)
     * @param  string $type Filter session logs for operation type (see table above for acceptable values) (optional)
     * @param  int $offset Offset of the records list (optional)
     * @param  int $limit Limit of the records list (optional)
     * @param  string $sort Comma separated list sort params (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSessionLogsAsync($evApiKey, $evAccessToken, $startDate = null, $endDate = null, $ipAddress = null, $username = null, $path = null, $type = null, $offset = null, $limit = null, $sort = null)
    {
        return $this->getSessionLogsAsyncWithHttpInfo($evApiKey, $evAccessToken, $startDate, $endDate, $ipAddress, $username, $path, $type, $offset, $limit, $sort)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getSessionLogsAsyncWithHttpInfo
     *
     * Get activity logs
     *
     * @param  string $evApiKey API Key (required)
     * @param  string $evAccessToken Access Token (required)
     * @param  \DateTime $startDate Start date of the filter data range (optional)
     * @param  \DateTime $endDate End date of the filter data range (optional)
     * @param  string $ipAddress Used to filter session logs by ip address. (optional)
     * @param  string $username Username used for filtering a list (optional)
     * @param  string $path Path used to filter records (optional)
     * @param  string $type Filter session logs for operation type (see table above for acceptable values) (optional)
     * @param  int $offset Offset of the records list (optional)
     * @param  int $limit Limit of the records list (optional)
     * @param  string $sort Comma separated list sort params (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSessionLogsAsyncWithHttpInfo($evApiKey, $evAccessToken, $startDate = null, $endDate = null, $ipAddress = null, $username = null, $path = null, $type = null, $offset = null, $limit = null, $sort = null)
    {
        $returnType = '\ExaVault\Model\SessionActivityResponse';
        $request = $this->getSessionLogsRequest($evApiKey, $evAccessToken, $startDate, $endDate, $ipAddress, $username, $path, $type, $offset, $limit, $sort);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getSessionLogs'
     *
     * @param  string $evApiKey API Key (required)
     * @param  string $evAccessToken Access Token (required)
     * @param  \DateTime $startDate Start date of the filter data range (optional)
     * @param  \DateTime $endDate End date of the filter data range (optional)
     * @param  string $ipAddress Used to filter session logs by ip address. (optional)
     * @param  string $username Username used for filtering a list (optional)
     * @param  string $path Path used to filter records (optional)
     * @param  string $type Filter session logs for operation type (see table above for acceptable values) (optional)
     * @param  int $offset Offset of the records list (optional)
     * @param  int $limit Limit of the records list (optional)
     * @param  string $sort Comma separated list sort params (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getSessionLogsRequest($evApiKey, $evAccessToken, $startDate = null, $endDate = null, $ipAddress = null, $username = null, $path = null, $type = null, $offset = null, $limit = null, $sort = null)
    {
        // verify the required parameter 'evApiKey' is set
        if ($evApiKey === null || (is_array($evApiKey) && count($evApiKey) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $evApiKey when calling getSessionLogs'
            );
        }
        // verify the required parameter 'evAccessToken' is set
        if ($evAccessToken === null || (is_array($evAccessToken) && count($evAccessToken) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $evAccessToken when calling getSessionLogs'
            );
        }

        $resourcePath = '/activity/session';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($startDate !== null) {
            $queryParams['startDate'] = ObjectSerializer::toQueryValue($startDate, 'date-time');
        }
        // query params
        if ($endDate !== null) {
            $queryParams['endDate'] = ObjectSerializer::toQueryValue($endDate, 'date-time');
        }
        // query params
        if ($ipAddress !== null) {
            $queryParams['ipAddress'] = ObjectSerializer::toQueryValue($ipAddress, null);
        }
        // query params
        if ($username !== null) {
            $queryParams['username'] = ObjectSerializer::toQueryValue($username, null);
        }
        // query params
        if ($path !== null) {
            $queryParams['path'] = ObjectSerializer::toQueryValue($path, null);
        }
        // query params
        if ($type !== null) {
            $queryParams['type'] = ObjectSerializer::toQueryValue($type, null);
        }
        // query params
        if ($offset !== null) {
            $queryParams['offset'] = ObjectSerializer::toQueryValue($offset, null);
        }
        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit, null);
        }
        // query params
        if ($sort !== null) {
            $queryParams['sort'] = ObjectSerializer::toQueryValue($sort, null);
        }
        // header params
        if ($evApiKey !== null) {
            $headerParams['ev-api-key'] = ObjectSerializer::toHeaderValue($evApiKey);
        }
        // header params
        if ($evAccessToken !== null) {
            $headerParams['ev-access-token'] = ObjectSerializer::toHeaderValue($evAccessToken);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getWebhookLogs
     *
     * Get webhook logs
     *
     * @param  string $evApiKey API Key (required)
     * @param  string $evAccessToken Access Token (required)
     * @param  \DateTime $startDate Earliest date of entries to include in list (optional)
     * @param  \DateTime $endDate Latest date of entries to include in list (optional)
     * @param  string $endpointUrl Webhook listener endpoint (optional)
     * @param  string $event Type of activity that triggered the webhook attempt (optional)
     * @param  int $statusCode Response code from the webhook endpoint (optional)
     * @param  string $resourcePath Path of the resource that triggered the webhook attempt (optional)
     * @param  string $username Filter by triggering username. (optional)
     * @param  int $offset Records to skip before returning results. (optional)
     * @param  int $limit Limit of the records list (optional)
     * @param  string $sort Comma separated list sort params (optional)
     *
     * @throws \ExaVault\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \ExaVault\Model\WebhookActivityResponse
     */
    public function getWebhookLogs($evApiKey, $evAccessToken, $startDate = null, $endDate = null, $endpointUrl = null, $event = null, $statusCode = null, $resourcePath = null, $username = null, $offset = null, $limit = null, $sort = null)
    {
        list($response) = $this->getWebhookLogsWithHttpInfo($evApiKey, $evAccessToken, $startDate, $endDate, $endpointUrl, $event, $statusCode, $resourcePath, $username, $offset, $limit, $sort);
        return $response;
    }

    /**
     * Operation getWebhookLogsWithHttpInfo
     *
     * Get webhook logs
     *
     * @param  string $evApiKey API Key (required)
     * @param  string $evAccessToken Access Token (required)
     * @param  \DateTime $startDate Earliest date of entries to include in list (optional)
     * @param  \DateTime $endDate Latest date of entries to include in list (optional)
     * @param  string $endpointUrl Webhook listener endpoint (optional)
     * @param  string $event Type of activity that triggered the webhook attempt (optional)
     * @param  int $statusCode Response code from the webhook endpoint (optional)
     * @param  string $resourcePath Path of the resource that triggered the webhook attempt (optional)
     * @param  string $username Filter by triggering username. (optional)
     * @param  int $offset Records to skip before returning results. (optional)
     * @param  int $limit Limit of the records list (optional)
     * @param  string $sort Comma separated list sort params (optional)
     *
     * @throws \ExaVault\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \ExaVault\Model\WebhookActivityResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getWebhookLogsWithHttpInfo($evApiKey, $evAccessToken, $startDate = null, $endDate = null, $endpointUrl = null, $event = null, $statusCode = null, $resourcePath = null, $username = null, $offset = null, $limit = null, $sort = null)
    {
        $returnType = '\ExaVault\Model\WebhookActivityResponse';
        $request = $this->getWebhookLogsRequest($evApiKey, $evAccessToken, $startDate, $endDate, $endpointUrl, $event, $statusCode, $resourcePath, $username, $offset, $limit, $sort);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ExaVault\Model\WebhookActivityResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getWebhookLogsAsync
     *
     * Get webhook logs
     *
     * @param  string $evApiKey API Key (required)
     * @param  string $evAccessToken Access Token (required)
     * @param  \DateTime $startDate Earliest date of entries to include in list (optional)
     * @param  \DateTime $endDate Latest date of entries to include in list (optional)
     * @param  string $endpointUrl Webhook listener endpoint (optional)
     * @param  string $event Type of activity that triggered the webhook attempt (optional)
     * @param  int $statusCode Response code from the webhook endpoint (optional)
     * @param  string $resourcePath Path of the resource that triggered the webhook attempt (optional)
     * @param  string $username Filter by triggering username. (optional)
     * @param  int $offset Records to skip before returning results. (optional)
     * @param  int $limit Limit of the records list (optional)
     * @param  string $sort Comma separated list sort params (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getWebhookLogsAsync($evApiKey, $evAccessToken, $startDate = null, $endDate = null, $endpointUrl = null, $event = null, $statusCode = null, $resourcePath = null, $username = null, $offset = null, $limit = null, $sort = null)
    {
        return $this->getWebhookLogsAsyncWithHttpInfo($evApiKey, $evAccessToken, $startDate, $endDate, $endpointUrl, $event, $statusCode, $resourcePath, $username, $offset, $limit, $sort)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getWebhookLogsAsyncWithHttpInfo
     *
     * Get webhook logs
     *
     * @param  string $evApiKey API Key (required)
     * @param  string $evAccessToken Access Token (required)
     * @param  \DateTime $startDate Earliest date of entries to include in list (optional)
     * @param  \DateTime $endDate Latest date of entries to include in list (optional)
     * @param  string $endpointUrl Webhook listener endpoint (optional)
     * @param  string $event Type of activity that triggered the webhook attempt (optional)
     * @param  int $statusCode Response code from the webhook endpoint (optional)
     * @param  string $resourcePath Path of the resource that triggered the webhook attempt (optional)
     * @param  string $username Filter by triggering username. (optional)
     * @param  int $offset Records to skip before returning results. (optional)
     * @param  int $limit Limit of the records list (optional)
     * @param  string $sort Comma separated list sort params (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getWebhookLogsAsyncWithHttpInfo($evApiKey, $evAccessToken, $startDate = null, $endDate = null, $endpointUrl = null, $event = null, $statusCode = null, $resourcePath = null, $username = null, $offset = null, $limit = null, $sort = null)
    {
        $returnType = '\ExaVault\Model\WebhookActivityResponse';
        $request = $this->getWebhookLogsRequest($evApiKey, $evAccessToken, $startDate, $endDate, $endpointUrl, $event, $statusCode, $resourcePath, $username, $offset, $limit, $sort);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getWebhookLogs'
     *
     * @param  string $evApiKey API Key (required)
     * @param  string $evAccessToken Access Token (required)
     * @param  \DateTime $startDate Earliest date of entries to include in list (optional)
     * @param  \DateTime $endDate Latest date of entries to include in list (optional)
     * @param  string $endpointUrl Webhook listener endpoint (optional)
     * @param  string $event Type of activity that triggered the webhook attempt (optional)
     * @param  int $statusCode Response code from the webhook endpoint (optional)
     * @param  string $resourcePath Path of the resource that triggered the webhook attempt (optional)
     * @param  string $username Filter by triggering username. (optional)
     * @param  int $offset Records to skip before returning results. (optional)
     * @param  int $limit Limit of the records list (optional)
     * @param  string $sort Comma separated list sort params (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getWebhookLogsRequest($evApiKey, $evAccessToken, $startDate = null, $endDate = null, $endpointUrl = null, $event = null, $statusCode = null, $resourcePath = null, $username = null, $offset = null, $limit = null, $sort = null)
    {
        // verify the required parameter 'evApiKey' is set
        if ($evApiKey === null || (is_array($evApiKey) && count($evApiKey) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $evApiKey when calling getWebhookLogs'
            );
        }
        // verify the required parameter 'evAccessToken' is set
        if ($evAccessToken === null || (is_array($evAccessToken) && count($evAccessToken) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $evAccessToken when calling getWebhookLogs'
            );
        }

        $resourcePath = '/activity/webhooks';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($startDate !== null) {
            $queryParams['startDate'] = ObjectSerializer::toQueryValue($startDate, 'date-time');
        }
        // query params
        if ($endDate !== null) {
            $queryParams['endDate'] = ObjectSerializer::toQueryValue($endDate, 'date-time');
        }
        // query params
        if ($endpointUrl !== null) {
            $queryParams['endpointUrl'] = ObjectSerializer::toQueryValue($endpointUrl, 'uri');
        }
        // query params
        if ($event !== null) {
            $queryParams['event'] = ObjectSerializer::toQueryValue($event, null);
        }
        // query params
        if ($statusCode !== null) {
            $queryParams['statusCode'] = ObjectSerializer::toQueryValue($statusCode, null);
        }
        // query params
        if ($resourcePath !== null) {
            $queryParams['resourcePath'] = ObjectSerializer::toQueryValue($resourcePath, null);
        }
        // query params
        if ($username !== null) {
            $queryParams['username'] = ObjectSerializer::toQueryValue($username, null);
        }
        // query params
        if ($offset !== null) {
            $queryParams['offset'] = ObjectSerializer::toQueryValue($offset, null);
        }
        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit, null);
        }
        // query params
        if ($sort !== null) {
            $queryParams['sort'] = ObjectSerializer::toQueryValue($sort, null);
        }
        // header params
        if ($evApiKey !== null) {
            $headerParams['ev-api-key'] = ObjectSerializer::toHeaderValue($evApiKey);
        }
        // header params
        if ($evAccessToken !== null) {
            $headerParams['ev-access-token'] = ObjectSerializer::toHeaderValue($evAccessToken);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
