<?php
/**
 * ShareAttributes
 *
 * PHP version 5
 *
 * @category Class
 * @package  ExaVault
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ExaVault API
 *
 * See our API reference documentation at https://www.exavault.com/developer/api-docs/
 *
 * OpenAPI spec version: 2.0
 * Contact: support@exavault.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.22
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace ExaVault\Model;

use \ArrayAccess;
use \ExaVault\ObjectSerializer;

/**
 * ShareAttributes Class Doc Comment
 *
 * @category Class
 * @description Attributes of the share including the name, path and share recipients.
 * @package  ExaVault
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ShareAttributes implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ShareAttributes';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'name' => 'string',
'hasPassword' => 'bool',
'public' => 'bool',
'accessMode' => '\ExaVault\Model\AccessMode',
'accessDescription' => 'string',
'embed' => 'bool',
'hash' => 'string',
'ownerHash' => 'string',
'expiration' => 'string',
'expired' => 'bool',
'resent' => '\DateTime',
'type' => 'string',
'requireEmail' => 'bool',
'fileDropCreateFolders' => 'bool',
'paths' => 'string[]',
'recipients' => '\ExaVault\Model\ShareRecipient[]',
'messages' => '\ExaVault\Model\ShareMessage[]',
'inherited' => 'bool',
'status' => 'int',
'hasNotification' => 'bool',
'created' => '\DateTime',
'modified' => '\DateTime',
'trackingStatus' => 'string',
'formId' => 'int'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'name' => null,
'hasPassword' => null,
'public' => null,
'accessMode' => null,
'accessDescription' => null,
'embed' => null,
'hash' => null,
'ownerHash' => null,
'expiration' => null,
'expired' => null,
'resent' => 'date-time',
'type' => null,
'requireEmail' => null,
'fileDropCreateFolders' => null,
'paths' => null,
'recipients' => null,
'messages' => null,
'inherited' => null,
'status' => 'int32',
'hasNotification' => null,
'created' => 'date-time',
'modified' => 'date-time',
'trackingStatus' => null,
'formId' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
'hasPassword' => 'hasPassword',
'public' => 'public',
'accessMode' => 'accessMode',
'accessDescription' => 'accessDescription',
'embed' => 'embed',
'hash' => 'hash',
'ownerHash' => 'ownerHash',
'expiration' => 'expiration',
'expired' => 'expired',
'resent' => 'resent',
'type' => 'type',
'requireEmail' => 'requireEmail',
'fileDropCreateFolders' => 'fileDropCreateFolders',
'paths' => 'paths',
'recipients' => 'recipients',
'messages' => 'messages',
'inherited' => 'inherited',
'status' => 'status',
'hasNotification' => 'hasNotification',
'created' => 'created',
'modified' => 'modified',
'trackingStatus' => 'trackingStatus',
'formId' => 'formId'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
'hasPassword' => 'setHasPassword',
'public' => 'setPublic',
'accessMode' => 'setAccessMode',
'accessDescription' => 'setAccessDescription',
'embed' => 'setEmbed',
'hash' => 'setHash',
'ownerHash' => 'setOwnerHash',
'expiration' => 'setExpiration',
'expired' => 'setExpired',
'resent' => 'setResent',
'type' => 'setType',
'requireEmail' => 'setRequireEmail',
'fileDropCreateFolders' => 'setFileDropCreateFolders',
'paths' => 'setPaths',
'recipients' => 'setRecipients',
'messages' => 'setMessages',
'inherited' => 'setInherited',
'status' => 'setStatus',
'hasNotification' => 'setHasNotification',
'created' => 'setCreated',
'modified' => 'setModified',
'trackingStatus' => 'setTrackingStatus',
'formId' => 'setFormId'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
'hasPassword' => 'getHasPassword',
'public' => 'getPublic',
'accessMode' => 'getAccessMode',
'accessDescription' => 'getAccessDescription',
'embed' => 'getEmbed',
'hash' => 'getHash',
'ownerHash' => 'getOwnerHash',
'expiration' => 'getExpiration',
'expired' => 'getExpired',
'resent' => 'getResent',
'type' => 'getType',
'requireEmail' => 'getRequireEmail',
'fileDropCreateFolders' => 'getFileDropCreateFolders',
'paths' => 'getPaths',
'recipients' => 'getRecipients',
'messages' => 'getMessages',
'inherited' => 'getInherited',
'status' => 'getStatus',
'hasNotification' => 'getHasNotification',
'created' => 'getCreated',
'modified' => 'getModified',
'trackingStatus' => 'getTrackingStatus',
'formId' => 'getFormId'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const TYPE_SHARED_FOLDER = 'shared_folder';
const TYPE_SEND = 'send';
const TYPE_RECEIVE = 'receive';
const STATUS_0 = 0;
const STATUS_1 = 1;
const TRACKING_STATUS_COMPLETE = 'complete';
const TRACKING_STATUS_INCOMPLETE = 'incomplete';
const TRACKING_STATUS_PENDING = 'pending';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_SHARED_FOLDER,
self::TYPE_SEND,
self::TYPE_RECEIVE,        ];
    }
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_0,
self::STATUS_1,        ];
    }
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTrackingStatusAllowableValues()
    {
        return [
            self::TRACKING_STATUS_COMPLETE,
self::TRACKING_STATUS_INCOMPLETE,
self::TRACKING_STATUS_PENDING,        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['hasPassword'] = isset($data['hasPassword']) ? $data['hasPassword'] : null;
        $this->container['public'] = isset($data['public']) ? $data['public'] : null;
        $this->container['accessMode'] = isset($data['accessMode']) ? $data['accessMode'] : null;
        $this->container['accessDescription'] = isset($data['accessDescription']) ? $data['accessDescription'] : null;
        $this->container['embed'] = isset($data['embed']) ? $data['embed'] : null;
        $this->container['hash'] = isset($data['hash']) ? $data['hash'] : null;
        $this->container['ownerHash'] = isset($data['ownerHash']) ? $data['ownerHash'] : null;
        $this->container['expiration'] = isset($data['expiration']) ? $data['expiration'] : null;
        $this->container['expired'] = isset($data['expired']) ? $data['expired'] : null;
        $this->container['resent'] = isset($data['resent']) ? $data['resent'] : null;
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
        $this->container['requireEmail'] = isset($data['requireEmail']) ? $data['requireEmail'] : null;
        $this->container['fileDropCreateFolders'] = isset($data['fileDropCreateFolders']) ? $data['fileDropCreateFolders'] : null;
        $this->container['paths'] = isset($data['paths']) ? $data['paths'] : null;
        $this->container['recipients'] = isset($data['recipients']) ? $data['recipients'] : null;
        $this->container['messages'] = isset($data['messages']) ? $data['messages'] : null;
        $this->container['inherited'] = isset($data['inherited']) ? $data['inherited'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['hasNotification'] = isset($data['hasNotification']) ? $data['hasNotification'] : null;
        $this->container['created'] = isset($data['created']) ? $data['created'] : null;
        $this->container['modified'] = isset($data['modified']) ? $data['modified'] : null;
        $this->container['trackingStatus'] = isset($data['trackingStatus']) ? $data['trackingStatus'] : null;
        $this->container['formId'] = isset($data['formId']) ? $data['formId'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($this->container['type']) && !in_array($this->container['type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'type', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'status', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getTrackingStatusAllowableValues();
        if (!is_null($this->container['trackingStatus']) && !in_array($this->container['trackingStatus'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'trackingStatus', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name Share name.
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets hasPassword
     *
     * @return bool
     */
    public function getHasPassword()
    {
        return $this->container['hasPassword'];
    }

    /**
     * Sets hasPassword
     *
     * @param bool $hasPassword True if the share has password.
     *
     * @return $this
     */
    public function setHasPassword($hasPassword)
    {
        $this->container['hasPassword'] = $hasPassword;

        return $this;
    }

    /**
     * Gets public
     *
     * @return bool
     */
    public function getPublic()
    {
        return $this->container['public'];
    }

    /**
     * Sets public
     *
     * @param bool $public True if the share has a public url.
     *
     * @return $this
     */
    public function setPublic($public)
    {
        $this->container['public'] = $public;

        return $this;
    }

    /**
     * Gets accessMode
     *
     * @return \ExaVault\Model\AccessMode
     */
    public function getAccessMode()
    {
        return $this->container['accessMode'];
    }

    /**
     * Sets accessMode
     *
     * @param \ExaVault\Model\AccessMode $accessMode accessMode
     *
     * @return $this
     */
    public function setAccessMode($accessMode)
    {
        $this->container['accessMode'] = $accessMode;

        return $this;
    }

    /**
     * Gets accessDescription
     *
     * @return string
     */
    public function getAccessDescription()
    {
        return $this->container['accessDescription'];
    }

    /**
     * Sets accessDescription
     *
     * @param string $accessDescription Description of the share access rights.
     *
     * @return $this
     */
    public function setAccessDescription($accessDescription)
    {
        $this->container['accessDescription'] = $accessDescription;

        return $this;
    }

    /**
     * Gets embed
     *
     * @return bool
     */
    public function getEmbed()
    {
        return $this->container['embed'];
    }

    /**
     * Sets embed
     *
     * @param bool $embed True if share can be embedded.
     *
     * @return $this
     */
    public function setEmbed($embed)
    {
        $this->container['embed'] = $embed;

        return $this;
    }

    /**
     * Gets hash
     *
     * @return string
     */
    public function getHash()
    {
        return $this->container['hash'];
    }

    /**
     * Sets hash
     *
     * @param string $hash Share hash.
     *
     * @return $this
     */
    public function setHash($hash)
    {
        $this->container['hash'] = $hash;

        return $this;
    }

    /**
     * Gets ownerHash
     *
     * @return string
     */
    public function getOwnerHash()
    {
        return $this->container['ownerHash'];
    }

    /**
     * Sets ownerHash
     *
     * @param string $ownerHash Share owner's hash.
     *
     * @return $this
     */
    public function setOwnerHash($ownerHash)
    {
        $this->container['ownerHash'] = $ownerHash;

        return $this;
    }

    /**
     * Gets expiration
     *
     * @return string
     */
    public function getExpiration()
    {
        return $this->container['expiration'];
    }

    /**
     * Sets expiration
     *
     * @param string $expiration Expiration date of the share.
     *
     * @return $this
     */
    public function setExpiration($expiration)
    {
        $this->container['expiration'] = $expiration;

        return $this;
    }

    /**
     * Gets expired
     *
     * @return bool
     */
    public function getExpired()
    {
        return $this->container['expired'];
    }

    /**
     * Sets expired
     *
     * @param bool $expired True if the share has expired.
     *
     * @return $this
     */
    public function setExpired($expired)
    {
        $this->container['expired'] = $expired;

        return $this;
    }

    /**
     * Gets resent
     *
     * @return \DateTime
     */
    public function getResent()
    {
        return $this->container['resent'];
    }

    /**
     * Sets resent
     *
     * @param \DateTime $resent Invitations resent date. Can be `null` if resent never happened.
     *
     * @return $this
     */
    public function setResent($resent)
    {
        $this->container['resent'] = $resent;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type Type of share.
     *
     * @return $this
     */
    public function setType($type)
    {
        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($type) && !in_array($type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'type', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets requireEmail
     *
     * @return bool
     */
    public function getRequireEmail()
    {
        return $this->container['requireEmail'];
    }

    /**
     * Sets requireEmail
     *
     * @param bool $requireEmail True if share requires email to access.
     *
     * @return $this
     */
    public function setRequireEmail($requireEmail)
    {
        $this->container['requireEmail'] = $requireEmail;

        return $this;
    }

    /**
     * Gets fileDropCreateFolders
     *
     * @return bool
     */
    public function getFileDropCreateFolders()
    {
        return $this->container['fileDropCreateFolders'];
    }

    /**
     * Sets fileDropCreateFolders
     *
     * @param bool $fileDropCreateFolders Flag to show if separate folders should be created for each file upload to receive folder.
     *
     * @return $this
     */
    public function setFileDropCreateFolders($fileDropCreateFolders)
    {
        $this->container['fileDropCreateFolders'] = $fileDropCreateFolders;

        return $this;
    }

    /**
     * Gets paths
     *
     * @return string[]
     */
    public function getPaths()
    {
        return $this->container['paths'];
    }

    /**
     * Sets paths
     *
     * @param string[] $paths Path to the shared resource in your account.
     *
     * @return $this
     */
    public function setPaths($paths)
    {
        $this->container['paths'] = $paths;

        return $this;
    }

    /**
     * Gets recipients
     *
     * @return \ExaVault\Model\ShareRecipient[]
     */
    public function getRecipients()
    {
        return $this->container['recipients'];
    }

    /**
     * Sets recipients
     *
     * @param \ExaVault\Model\ShareRecipient[] $recipients Array of recipients.
     *
     * @return $this
     */
    public function setRecipients($recipients)
    {
        $this->container['recipients'] = $recipients;

        return $this;
    }

    /**
     * Gets messages
     *
     * @return \ExaVault\Model\ShareMessage[]
     */
    public function getMessages()
    {
        return $this->container['messages'];
    }

    /**
     * Sets messages
     *
     * @param \ExaVault\Model\ShareMessage[] $messages Array of invitation messages.
     *
     * @return $this
     */
    public function setMessages($messages)
    {
        $this->container['messages'] = $messages;

        return $this;
    }

    /**
     * Gets inherited
     *
     * @return bool
     */
    public function getInherited()
    {
        return $this->container['inherited'];
    }

    /**
     * Sets inherited
     *
     * @param bool $inherited True if share inherited from parent folder.
     *
     * @return $this
     */
    public function setInherited($inherited)
    {
        $this->container['inherited'] = $inherited;

        return $this;
    }

    /**
     * Gets status
     *
     * @return int
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param int $status Share activity status. Can be active (1) or deactivated (0).
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($status) && !in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'status', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets hasNotification
     *
     * @return bool
     */
    public function getHasNotification()
    {
        return $this->container['hasNotification'];
    }

    /**
     * Sets hasNotification
     *
     * @param bool $hasNotification True if share has notification.
     *
     * @return $this
     */
    public function setHasNotification($hasNotification)
    {
        $this->container['hasNotification'] = $hasNotification;

        return $this;
    }

    /**
     * Gets created
     *
     * @return \DateTime
     */
    public function getCreated()
    {
        return $this->container['created'];
    }

    /**
     * Sets created
     *
     * @param \DateTime $created Timestamp of share creation.
     *
     * @return $this
     */
    public function setCreated($created)
    {
        $this->container['created'] = $created;

        return $this;
    }

    /**
     * Gets modified
     *
     * @return \DateTime
     */
    public function getModified()
    {
        return $this->container['modified'];
    }

    /**
     * Sets modified
     *
     * @param \DateTime $modified Timestamp of share modification. Can be `null` if it wasn't modified.
     *
     * @return $this
     */
    public function setModified($modified)
    {
        $this->container['modified'] = $modified;

        return $this;
    }

    /**
     * Gets trackingStatus
     *
     * @return string
     */
    public function getTrackingStatus()
    {
        return $this->container['trackingStatus'];
    }

    /**
     * Sets trackingStatus
     *
     * @param string $trackingStatus Checks recipient received status and returns whether it's been received (`complete`,) partial received (`incomplete`,) or not received yet (`pending`.)
     *
     * @return $this
     */
    public function setTrackingStatus($trackingStatus)
    {
        $allowedValues = $this->getTrackingStatusAllowableValues();
        if (!is_null($trackingStatus) && !in_array($trackingStatus, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'trackingStatus', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['trackingStatus'] = $trackingStatus;

        return $this;
    }

    /**
     * Gets formId
     *
     * @return int
     */
    public function getFormId()
    {
        return $this->container['formId'];
    }

    /**
     * Sets formId
     *
     * @param int $formId ID of the form.
     *
     * @return $this
     */
    public function setFormId($formId)
    {
        $this->container['formId'] = $formId;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
